# Generated by Django 5.2.12 on 2026-03-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_member_college_name_member_membership_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
